table Category
	lineageTag: 5514005a-eee4-4b0d-ab5c-e7e509991e34

	column CategoryID
		dataType: int64
		formatString: 0
		lineageTag: ee2a795c-4662-431f-8714-ca917167558e
		summarizeBy: none
		sourceColumn: CategoryID

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: 7e9ab234-d363-41a7-bf7f-d31b8e7623ff
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 9e025939-7943-4229-8099-9b7ae9637769
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition Category = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("Z:\DAXChallenge.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "Category", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"CategoryID", Int64.Type}, {"CategoryName", type text}, {"Description", type text}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

