table Customers
	lineageTag: 9c467931-e09a-4f16-a7db-84cfe6bd404f

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 26655449-c0d4-454d-94fc-c98b24452c34
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 7cbe3fec-2618-484b-9342-a7769caa4f9c
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 7eabadaa-8bfd-43e3-aa68-7ba137e3238c
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: c5bc8814-94cd-43d9-a09e-b372078deb27
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: d712cba6-408d-4a79-8ab4-de785b7b857f
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("Z:\DAXChallenge.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "Customers", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"CustomerID", Int64.Type}, {"CustomerName", type text}, {"City", type text}, {"State", type text}, {"Country", type text}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

